name: NPM Publish
on: [push]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - run: npm publish
        working-directory: ../
        env:
          NODE_AUTH_TOKEN: '${{secrets.npm_token}}'