name: NPM Publish
working-directory: ./
on:
  push:
    tags:
      - v*
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: '${{secrets.npm_token}}'